version: '3'
services:
  portfolio-web:
    build: .
    restart: unless-stopped
    container_name: portfolio-web
    ports:
     - "3471:80"
    environment:
     APP_KEY: base64:Hsn2BwXdpKHhEiTSDkkuWP1OwbfcZZFQlLoWbjY4lk8=
     REDIS_HOST: portfolio-redis
     ASSET_URL: https://andyh.app
     CACHE_DRIVER: redis
    volumes:
      - .:/app
    depends_on:
      - portfolio-redis
  portfolio-redis:
    image: redis:6.0.4
    restart: unless-stopped
    container_name: portfolio-redis