version: '3'
services:
  portfolio-web:
    image: andy3471/andyh-portfolio
    restart: unless-stopped
    container_name: portfolio-web
    ports:
     - "3471:80"
    environment:
     APP_KEY: base64:Hsn2BwXdpKHhEiTSDkkuWP1OwbfcZZFQlLoWbjY4lk8=
     REDIS_HOST: portfolio-redis
     ASSET_URL: http://localhost:3471
     CACHE_DRIVER: redis
     APP_ENV: local
    volumes:
      - .:/app
    depends_on:
      - portfolio-redis
  portfolio-redis:
    image: redis:6.0.4
    restart: unless-stopped
    container_name: portfolio-redis